### PR TITLE
Join game

### PR DESCRIPTION
**Pull request by racheldk**
- [ ] Join button on Games list and on Game Detail modal sends POST request
- [ ] User gets confirmation screen with game details 
- [ ] link on confirmation screen takes user back to /my-games

### CODE REVIEW

**Comment by Carlos-Tirado** [comment]
cool!

**Comment by racheldk** [comment]
I currently have the confirmation showing the host's first name. Do we want it to show the username instead?

**Comment by Carlos-Tirado** [comment]
I think username sounds good, If the user wanna know other's name users could they see it in their profile?

**Comment by racheldk** [comment]
discussed in FE meeting

**Pull request merged**
